### ISSUE TITLE
Project is complete waiting for response

### ISSUE THREAD

**Issue by farkas1070** [Teaching-projects/SOE-ProgAlap2-2021-Winamp#1]

**Comment by hegyhati** [comment]
Na, mielott jobban megcsamcsognam, visszadobom a labdat:

Eloszor is, kellene egy readme, ami leir dolgokat, szeretnek latni koddokumentaciot.

Mivel hasznalsz egy csomo package-et, a readme-ben illik leirni, miket, hogyan kellene feltelepiteni, hogy mukodokepes legyen a dolog (nalam Pillow volt, de imagetk, mutagen, pygame pl nem.)

Miutan mindent sikerult feltennem, ez tortent:

```
hegyhati@TarAmon:~/git/tmp/SOE-ProgAlap2-2021-Winamp$ python3 mp3player.py 
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "mp3player.py", line 547, in <module>
    layout = Layout()
  File "mp3player.py", line 45, in __init__
    with open(self.filename,"rt") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hegyhati/git/tmp/SOE-ProgAlap2-2021-Winamp\\playlist.json'
hegyhati@TarAmon:~/git/tmp/SOE-ProgAlap2-2021-Winamp$ 
```
Tessek hasznalni az `os.path`-ot osszefuzesre, hogy minden platformon megfeleloen mukodjanek a dolgok. 

Ha ezek megvannak, irj, es lesem :)

**Comment by farkas1070** [comment]
Kész vagyok tanár úr, remélem már így működni fog, valamint feltöltöttem a dokumentációt, és csináltam readmet is amibe beletettem hogy miért kellenek, és hogyan lehet őket letölteni

**Comment by hegyhati** [comment]
![image](https://user-images.githubusercontent.com/13832329/121528821-1b2fef80-c9fc-11eb-99cd-9e3a62c02f67.png)

Pedig en a kodnezegetes kozben nagyon akartam errol hallgatni a zenet... 

No, a kodot erintoen: NAAAAAAGGGYYYOOON hosszu ez a kod igy egyben. 400+ sor, amibol 150 az init script. Vagd szet kissebb, maintainelhetobb darabokra. 

Peldaul vannak Frame-jeid., azokat szedd ki kulon osztalyba, azok inicializaljak magukat, es akkor csak azokat kell rapakolni a foablakra. 

Aztan van pl ez a resz:

```python
        raw_playbutton = Image.open(os.path.join(f"{self.images_folder_path}", "4.png"))
        raw_pausebutton = Image.open(os.path.join(f"{self.images_folder_path}", "5.png"))
        raw_unpausebutton = Image.open(os.path.join(f"{self.images_folder_path}", "1.png"))
        raw_nextbutton = Image.open(os.path.join(f"{self.images_folder_path}", "2.png"))
        raw_previousbutton = Image.open(os.path.join(f"{self.images_folder_path}", "3.png"))
        raw_loopbutton = Image.open(os.path.join(f"{self.images_folder_path}", "7.png"))
        raw_shufflebutton = Image.open(os.path.join(f"{self.images_folder_path}", "6.png"))
        raw_disabled_back_button = Image.open(os.path.join(f"{self.images_folder_path}", "8.png"))
        raw_normal_back_button = Image.open(os.path.join(f"{self.images_folder_path}", "9.png"))

        #resizing the image with antialising

        resized_playbutton = raw_playbutton.resize((40,40),Image.ANTIALIAS)
        resized_pausebutton = raw_pausebutton.resize((40,40),Image.ANTIALIAS)
        resized_unpausebutton = raw_unpausebutton.resize((40,40),Image.ANTIALIAS)
        resized_nextbutton = raw_nextbutton.resize((40,40),Image.ANTIALIAS)
        resized_previousbutton = raw_previousbutton.resize((40,40),Image.ANTIALIAS)
        resized_loopbutton = raw_loopbutton.resize((50,50),Image.ANTIALIAS)
        resized_shufflebutton = raw_shufflebutton.resize((50,50),Image.ANTIALIAS)
        resized_disabled_back_button = raw_disabled_back_button.resize((50,50),Image.ANTIALIAS)
        resized_normal_back_button = raw_normal_back_button.resize((50,50),Image.ANTIALIAS)

        # getting the image that will be used

        self.playbutton_im = ImageTk.PhotoImage(resized_playbutton)
        self.pausebutton_im = ImageTk.PhotoImage(resized_pausebutton)
        self.unpausebutton_im = ImageTk.PhotoImage(resized_unpausebutton)
        self.nextbutton_im = ImageTk.PhotoImage(resized_nextbutton)
        self.previousbutton_im = ImageTk.PhotoImage(resized_previousbutton)
        self.loopbutton_im = ImageTk.PhotoImage(resized_loopbutton)
        self.shufflebutton_im = ImageTk.PhotoImage(resized_shufflebutton)
        self.disabled_back_button_im = ImageTk.PhotoImage(resized_disabled_back_button)
        self.normal_back_button_im = ImageTk.PhotoImage(resized_normal_back_button)

        #pygame event
        self.SONG_END = pygame.USEREVENT + 1
        pygame.mixer.music.set_endevent(self.SONG_END)
        

        #buttons on the third frame
        self.pause_button = tk.Button(self.bottomframe,image =self.pausebutton_im,borderwidth = 0,command = self.stop_button_pressed)
        self.pause_button.grid(row = 0,column = 2,padx = 5)
        self.unpause_button = tk.Button(self.bottomframe,image =self.unpausebutton_im,borderwidth = 0,command = self.unstop_button_pressed)
        self.unpause_button.grid(row = 0,column = 3,padx = 5)
        self.play_button = tk.Button(self.bottomframe,image =self.playbutton_im,borderwidth = 0,command =self.play_button_pressed)
        self.play_button.grid(row = 0,column = 1,padx = 5)
        self.next_button = tk.Button(self.bottomframe,image = self.nextbutton_im,borderwidth = 0,command =self.next_button_pressed)
        self.next_button.grid(row = 0,column = 4,padx = 5)
        self.previous_button = tk.Button(self.bottomframe,image = self.previousbutton_im,borderwidth = 0,command = self.previous_button_pressed)
        self.previous_button.grid(row = 0,column = 0,padx = 5)
        self.loop_button = tk.Checkbutton(self.bottomframe,image = self.loopbutton_im,variable = self.loopvar,onvalue = 1,offvalue = 0,borderwidth = 0,command = self.loop_button_pressed)
        self.loop_button.grid(row = 0,column = 5,padx = 5)
        self.shuffle_button = tk.Checkbutton(self.bottomframe,image = self.shufflebutton_im,variable = self.shufflevar,onvalue = 1,offvalue = 0,borderwidth = 0,command = self.shuffle_button_pressed)
        self.shuffle_button.grid(row = 0,column = 6,padx = 5)
        self.back_button = tk.Button(self.bottomframe,image = self.disabled_back_button_im,borderwidth = 0, state = tk.DISABLED,command = self.back_button_pressed)
        self.back_button.grid(row = 0,column = 7,padx = 5)
        self.current_label = tk.Label(self.title_frame,text = "All Songs: ")
        self.current_label.grid(row = 0,column = 0)
 ```

Na, ez pl 50 sor, es van csomo ismeltodo. Ezt lehetne sokkal szebben. Otletek igy "from the top of my head":
 - beteszed a cuccokat egy listaba, es szimplan egy ciklussal vegigmesz rajtuk (lasd pl a megoldasaimat a felevben)
 - Csinalhatnal egy `uiconfig.json`-t, amiben le van irva, hogy milyen gombok vannak, melyikhez melyik kep tartozik, mekkorara kell meretezni, A program azt beolvassa, es az alapjan tolti fel mondjuk a `self.buttons` dict-et pl. es akkor `self.play_button` helyett `self.buttons["play"]`-ed lesz mondjuk. (Meg lehet oldani az elsot is, egyik oran beszeltunk rola, de nem erdemes most it.)

Van, amikor feldobalsz ablakokat, pl a create window, vagy az add_favorites. Ezeket a specko window-kat szinten ki lehetne tenni egy kulon osztalyba, es itt csak egy sorban letrehozni beloluk egy peldanyt.

Ha jol latom, masodpercenkent meghivod ezt a check_event-et, hogyha a pygame dob egy song_end-et, akkor menjen a kovetkezo szamra. Nem lehetne valahogy ezt bind-olni inkabb?

Erzek nemi redundanciat a prev/next button-os dologban. 

Nem ertek a pygame-hez, de biztos, hogy egeszseges, hogy a volume-nal is initeled? 

Amugy nagyon franko, de most ezek jutottak eszembe, ha valami nem vilagos, kerdezz! :-)

**Comment by farkas1070** [comment]
Végigmentem a kódon, és az initet szétszedtem 6 különböző részre, a frameket és a new window-t kiszedtem külön osztályba, a frameket, és a gombokat szebben for ciklussal megcsináltam.

A check event másodpercenkénti meghívása eredetileg azért lett beletéve, hogy a scale ami jelzi lennt a szám állását másodpercben updatelve legyen, és ha már ott van ez akkor azért tettem bele oda a song_endet hogy akkor 2 dolgot végezzen egyszerre. 

a volume initelés kiszedtem és csak a legelején 1 initelés történik.

A redundanciát kiszedtem a prev és next buttonből és kitettem egy kis változtatással egy külön függvénybe ami meg van hívva mindd a kettőnél. 

A pygame error amit kaptál az pedig ha jól értettem a pygame hibája, ugyanis elég kevés audio formátumot támogat

a kóddokumentáció ki lett csreélve a frissre.

**Comment by hegyhati** [comment]
Az init atszervezesnel nem igy gondoltam, majd egyszer amikor Te meg en is jobban raerunk, ha van kedved szolj majd ram, es atbeszeljuk. Ettol fuggetlenul nem kerdes, hogy otos, szep munka.
